-- Script para ejecutar en el SQL Editor de Supabase
-- Crea la tabla 'logs' para guardar los entrenamientos y sesiones de surf

CREATE TABLE IF NOT EXISTS public.logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date text NOT NULL,
    "blockId" text NOT NULL,
    "surfData" jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Configura los permisos (RLS - Row Level Security) para permitir que la app lea y escriba sin autenticación
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

-- Permitir a cualquiera ver los datos (Lectura)
CREATE POLICY "Permitir lectura anonima"
ON public.logs FOR SELECT 
TO anon, authenticated
USING (true);

-- Permitir a cualquiera insertar datos (Escritura)
CREATE POLICY "Permitir insercion anonima"
ON public.logs FOR INSERT 
TO anon, authenticated
WITH CHECK (true);
